# Generated by Django 5.2.1 on 2025-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('featured', 'Featured Products'), ('best_sellers', 'Best Sellers')], default='new_arrivals', max_length=20),
        ),
    ]
